name: iOS-ipa-build

on:
  workflow_dispatch:
  
jobs:
  release:
    runs-on: macos-latest # or whichever runner you are using
    permissions:
      contents: write  # This is the critical line
    steps:
      - uses: actions/checkout@v3
      
      # ... your build steps for iOS ...

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
